---
title: "Social_marketing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(FactoMineR)
library(RColorBrewer)
library(cluster)
library(pvclust)
library(xtable)
library(plyr)
social_marketing <- read.csv("social_marketing.csv")
social_marketing$adult<- NULL
social_marketing$spam <- NULL
social_marketing$uncategorized<- NULL
social_marketing$chatter<- NULL
```

```{r}
apply(social_marketing[,-1],2,mean) 
apply(social_marketing[,-1],2,var)  
cor_socialm = cor(social_marketing[,-1])
cor_socialm
```

```{r}
pr.out=prcomp(social_marketing[,-1],scale=TRUE)
names(pr.out)
pr.out$rotation
biplot(pr.out,scale=0)
```

```{r}
pcl=pr.out$rotation
pcl
a=pcl[,1]
b=pcl[,2]
c=pcl[,3]
pc=cbind(a,b,c)
```

```{r}
wss <- (nrow(pc)-1)*sum(apply(pc,2,var))
for (i in 2:15) wss[i] <- sum(kmeans(pc,
                                     centers=i)$withinss)
plot(1:15, wss, type="b", xlab="Number of Clusters",
     ylab="Within groups sum of squares")
```