---
title: "ST380_HW2_Liu"
author: "Lufang Liu"
date: "8/17/2017"
output: pdf_document
---

# We start the analysis by 
```{r}
library(tm)
readerPlain = function(fname){
				readPlain(elem=list(content=readLines(fname)), 
							id=fname, language='en') }

author_dirs_train = Sys.glob('~/GitHub_Desktop/STA380/data/ReutersC50/C50train/*')
author_dirs_test = Sys.glob('~/GitHub_Desktop/STA380/data/ReutersC50/C50test/*')

file_list = NULL
labels = NULL

for(author in author_dirs_train) {
	author_name = substring(author, first=29)
	files_to_add = Sys.glob(paste0(author, '/*.txt'))
	file_list = append(file_list, files_to_add)
	labels = append(labels, rep(author_name, length(files_to_add)))
}

for(author in author_dirs_test) {
	author_name = substring(author, first=29)
	files_to_add = Sys.glob(paste0(author, '/*.txt'))
	file_list = append(file_list, files_to_add)
	labels = append(labels, rep(author_name, length(files_to_add)))
}

all_docs_train = lapply(file_list, readerPlain) 
all_docs_test = lapply(file_list, readerPlain) 

names(all_docs)_train = file_list
names(all_docs) = sub('.txt', '', names(all_docs))

my_corpus = Corpus(VectorSource(all_docs))
names(my_corpus) = file_list

```

```{r}




```

